// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toineffabdvvtwfngmkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvaW5lZmZhYmR2dnR3Zm5nbWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjY0NTMsImV4cCI6MjA2OTkwMjQ1M30.P2wcVpnvmCHpE1ua66ySZLyNOZR2HVgv1CBRGLxzVP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});