// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzcqeburlsfwibrhtmdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6Y3FlYnVybHNmd2licmh0bWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1Mzk3NjMsImV4cCI6MjA2NjExNTc2M30.KjGuJXaUwUHTJWy0oacwtyB_8Ev7V3eygz0r60u1IRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});