// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfwncmjacpxrjhqzvsyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtmd25jbWphY3B4cmpocXp2c3lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzMTIzNTgsImV4cCI6MjA4MDg4ODM1OH0.7jcrtdAKW9AI4BR_q1uPtkZ1BFMoP1BZdFP83e9F0xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});